### ISSUE TITLE
Can't export library definition since 12.x (`Gradle#projectsEvaluated(Action) on build 'Project' cannot be executed in the current context.`)

### ISSUE THREAD

**Issue by opatry** [mikepenz/AboutLibraries#1144]
**Edit 2025-04-25:**

> [!TIP]
> **TL;DR**
> The issue came from Gradle configuration on demand (`org.gradle.configureondemand=true`).
> Disabling it fixes the issue.
> A refactor of the plugin should allow taking this into account most likely in final `12.1.x`

---

I was using `11.5.0` it worked, I updated to `11.6.3`, it still works.
When updating to 12.0.0 (also reproduced with `12.0.1` and `12.1.0-rc01`.

```bash
./gradlew :tasks-app-android:exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/assets

...

* Where:
Build file '/Users/..../tasks-core/build.gradle.kts' line: 24

* What went wrong:
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.multiplatform', version: '2.1.20']
> Failed to apply plugin 'org.jetbrains.kotlin.multiplatform'.
   > Gradle#projectsEvaluated(Action) on build 'Taskfolio' cannot be executed in the current context.
```

Same is for desktop.

You can reach the project to reproduce here:
- https://github.com/opatry/taskfolio/pull/98
Just update `about-libraries` to `12.0.1` and run the Gradle task.

The `tasks-core/build.gradle.kts` is a Kotlin multiplatform library module which depends on few other KMP library modules.
I have 2 app projects, 1 for desktop, 1 for android.
Both depends on a KMP shared module which itself depends on the `tasks-core` one.

```
Failed to retrieve dependencies for storeReleaseUnitTest
org.gradle.api.internal.artifacts.ivyservice.TypedResolveException: Could not resolve all dependencies for configuration ':tasks-app-android:storeReleaseUnitTestRuntimeClasspath'.
...
Caused by: org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':tasks-core'.
...
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/...../tasks-core/build.gradle.kts' line: 24
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.multiplatform', version: '2.1.20']
...
Caused by: org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.multiplatform', version: '2.1.20']
...
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'org.jetbrains.kotlin.multiplatform'.
...
Caused by: org.gradle.api.internal.DefaultMutationGuard$IllegalMutationException: Gradle#projectsEvaluated(Action) on build 'Project' cannot be executed in the current context.


....

* Where:
Build file '/Users/..../tasks-core/build.gradle.kts' line: 24

* What went wrong:
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.multiplatform', version: '2.1.20']
> Failed to apply plugin 'org.jetbrains.kotlin.multiplatform'.
   > Gradle#projectsEvaluated(Action) on build 'Taskfolio' cannot be executed in the current context.
```

The dependencies if that helps.

```toml
[versions]
tasksApp-name = "1.2.2"
compileSdk = "36"
minSdk = "24"
targetSdk = "36"
agp = "8.9.2"
kotlin = "2.1.20"
ksp = "2.1.20-2.0.0"
coroutines = "1.10.2"
ktor = "3.1.2"
activity-compose = "1.11.0-rc01"
compose-plugin = "1.8.0-beta02"
compose-m3-adaptive = "1.1.0-beta02"
room = "2.7.1"
sqlite = "2.5.0"
koin = "4.0.4"
coil = "3.1.0"
about-libraries = "12.1.0-rc01"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.2" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.8.1" }

ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-htmlBuilder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
ktor-server-statusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

slf4j-nop = { module = "org.slf4j:slf4j-nop", version = "2.0.17" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

jetbrains-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.8.4" }
jetbrains-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.9.0-alpha16" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-test = { module = "io.insert-koin:koin-test" }

compose-m3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "compose-m3-adaptive" }
compose-m3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "compose-m3-adaptive" }
compose-m3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "compose-m3-adaptive" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version = "33.12.0" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

play-services-auth = { module = "com.google.android.gms:play-services-auth", version = "21.3.0" }

about-libraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "about-libraries" }

androidx-test-core = { module = "androidx.test:core", version = "1.6.1" }

[bundles]
ktor-server = ["ktor-server-core", "ktor-server-cio"]
ktor-client = [
    "ktor-client-core",
    "ktor-client-auth",
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-client-encoding",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json",
]

coil = ["coil-compose", "coil-network"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.3" }
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries" }
```
